
ReverseProxy:
    Routes:
        product-service:
            ClusterId: product-service
            Match:
                Path: 'product-api/{**remainder}'
            Transforms:
                - PathRemovePrefix: '/product-api'
                - PathPrefix: '/'
                - RequestHeaderOriginalHost: true
                  
        counter-service:
            ClusterId: counter-service
            Match:
                Path: 'counter-api/{**remainder}'
            Transforms:
                -   PathRemovePrefix: '/counter-api'
                -   PathPrefix: '/'
                -   RequestHeaderOriginalHost: true
#    Clusters:
#        product-service:
#            Destinations:
#                product-service-1:
#                    Address: http://localhost:5001
#        counter-service:
#            Destinations:
#                counter-service-1:
#                    Address: http://localhost:5002

