@host = http://localhost:5000
### Get token
# dotnet user-jwts create --claim "myCustomClaim=green"
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkxldmluIiwic3ViIjoiTGV2aW4iLCJqdGkiOiIzYTFhYjQ5YSIsIm15Q3VzdG9tQ2xhaW0iOiJncmVlbiIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MCIsIm5iZiI6MTY4NDE2NTc2OCwiZXhwIjoxNjkyMTE0NTY4LCJpYXQiOjE2ODQxNjU3NjgsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.06e4Hvl8hhb3srMVTZ5vdwm2gp4HHAt5JOyR8O8gQik

###
GET {{host}}/product-api/v1/api/item-types HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

###
GET {{host}}/product-api/v1/api/items-by-types/1,2,3 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}


###
POST {{host}}/counter-api/v1/api/orders HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "commandType": 0,
  "orderSource": 1,
  "location": 1,
  "loyaltyMemberId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "baristaItems": [
    {
      "itemType": {{$randomInt 0 5}}
    },
    {
      "itemType": {{$randomInt 0 5}}
    }
  ],
  "kitchenItems": [
    {
      "itemType": {{$randomInt 6 9}}
    }
  ],
  "timestamp": "2022-07-04T11:38:00.210Z"
}

###
GET {{host}}/counter-api/v1/api/fulfillment-orders HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}