version: "3.8"
services:
    
    postgresql:
        image: postgres:14-alpine
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=P@ssw0rd
        ports:
            - 5432:5432
        networks:
            - coffeeshop-network

    rabbitmq:
        image: masstransit/rabbitmq:latest
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - coffeeshop-network
            
    
    # Zipkin
    zipkin-all-in-one:
        image: openzipkin/zipkin:latest
        ports:
            - "9411:9411"
        networks:
            - coffeeshop-network
    
    # Jaeger
    jaeger-all-in-one:
        image: jaegertracing/all-in-one:latest
        ports:
            - "16686:16686"
            - "14268"
            - "14250"
        networks:
            - coffeeshop-network
    # Collector
    otel-collector:
        image: otel/opentelemetry-collector-contrib-dev:latest
        command: [ "--config=/etc/otel-collector-config.yaml", "" ]
        volumes:
            - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
        ports:
            - "1888:1888"   # pprof extension
            - "8888:8888"   # Prometheus metrics exposed by the collector
            - "8889:8889"   # Prometheus exporter metrics
            - "13133:13133" # health_check extension
            - "4317:4317"   # OTLP gRPC receiver
            - "55679:55679" # zpages extension
        depends_on:
            - jaeger-all-in-one
            - zipkin-all-in-one
        networks:
            - coffeeshop-network

    prometheus:
        container_name: prometheus
        image: prom/prometheus:latest
        volumes:
            - ./prometheus.yaml:/etc/prometheus/prometheus.yml
        ports:
            - "9090:9090"
        networks:
            - coffeeshop-network

    elk:
        image: sebp/elk:latest
        ports:
            - "5601:5601"
            - "9200:9200"
            - "5044:5044"
        networks:
            - coffeeshop-network

networks:
    coffeeshop-network:
